### ISSUE TITLE
Training SVMs for the results table

### ISSUE THREAD

**Issue by andreasvlachos** [elleryjsmith/UCLMCTest#22]
In order to be comparable to previous work we should train on mc160.train when testing on mc160.dev or mc160.test and train on mc500.train when testing on mc160.dev or mc160.test.

**Comment by andreasvlachos** [comment]
Also, remove the number for performance on train for SVMs, as it doesn’t make sense.

**Comment by nicola** [comment]
Fixed in https://github.com/nicola/UCLMCTest/commit/e892e6e19c88b22edaebd2d4d90e3b537a8cb654, pending PR #28

New SVM results here: https://github.com/nicola/UCLMCTest/blob/5f4fa8cef3a0fecf6aa49d76652f5a1b87908ca4/Results.md

**Comment by nicola** [comment]
Fixed again in #30
