### ISSUE TITLE
32 questions and 53 answers

### ISSUE THREAD

**Issue by nicola** [elleryjsmith/UCLMCTest#3]
When running this:

```
 jython -Dpython.path=stanford-parser.jar:stanford-parser-3.5.0-models.jar baseline.py
```

I get

```
Questions answered: 53
Correct Answers: 32
Result: 60%
```

So I checked how many questions were in there, and it said 120, are we missing 40 of them?

**Comment by elleryjsmith** [comment]
There's a line "mode == Question.MULTIPLE", this specifies the type of question that it answers. This is whether it requires one sentence to answer, or multiple. I've set it to do only one type at a time, so I could compare it with the results in the MCTest paper. You can take out that line to do all types of questions, or change it to Question.SINGLE.

Of course, it performs worse on the multiple-sentence questions, but so does the baseline in the paper, as far as I know.

**Comment by nicola** [comment]
Hey Ellery, I update the question a second before you answered.
My worry was on the questions being 120 and not 160 as in the file

**Comment by elleryjsmith** [comment]
So in most stories it only answers 2, 1 or 0 questions, based on the question type. This system was only designed for single-sentence questions mostly, but it still gets ~50% if multiple-sentence questions are included.

**Comment by elleryjsmith** [comment]
Oh, well in the dev set, there isnt the full 160 - it's split between mc160.train mc160.dev and mc160.test, giving 160 in total

**Comment by nicola** [comment]
great, thanks!
